START TRANSACTION;

CREATE TABLE "Worklogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NULL,
    "EndedAt" timestamp with time zone NOT NULL,
    "IssueId" integer NOT NULL,
    "StartedAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "CreatedById" uuid NOT NULL,
    "Deleted" boolean NOT NULL DEFAULT FALSE,
    "DeletedAt" timestamp with time zone NULL,
    "DeletedById" uuid NULL,
    "UpdatedAt" timestamp with time zone NULL,
    "UpdatedById" uuid NULL,
    "Uuid" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "Version" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Worklogs" PRIMARY KEY ("Id"),
    CONSTRAINT "CHK_Worklogs_StartedEnded" CHECK ("StartedAt" < "EndedAt"),
    CONSTRAINT "FK_Worklogs_Issues_IssueId" FOREIGN KEY ("IssueId") REFERENCES "Issues" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Worklogs_CreatedById" ON "Worklogs" ("CreatedById");

CREATE INDEX "IX_Worklogs_Deleted" ON "Worklogs" ("Deleted");

CREATE INDEX "IX_Worklogs_DeletedById" ON "Worklogs" ("DeletedById");

CREATE INDEX "IX_Worklogs_IssueId" ON "Worklogs" ("IssueId");

CREATE INDEX "IX_Worklogs_UpdatedById" ON "Worklogs" ("UpdatedById");

CREATE UNIQUE INDEX "IX_Worklogs_Uuid" ON "Worklogs" ("Uuid");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220506033048_CreateWorklogTable', '6.0.4');

COMMIT;
