START TRANSACTION;

CREATE TABLE "Issues" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NULL,
    "DueDate" timestamp with time zone NULL,
    "Estimate" integer NULL,
    "Name" character varying(100) NOT NULL,
    "Number" integer NOT NULL,
    "ProjectId" integer NOT NULL,
    "Score" double precision NULL,
    "TypeId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "CreatedById" uuid NOT NULL,
    "Deleted" boolean NOT NULL DEFAULT FALSE,
    "DeletedAt" timestamp with time zone NULL,
    "DeletedById" uuid NULL,
    "UpdatedAt" timestamp with time zone NULL,
    "UpdatedById" uuid NULL,
    "Uuid" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "Version" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Issues" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Issues_IssueTypes_TypeId" FOREIGN KEY ("TypeId") REFERENCES "IssueTypes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Issues_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Issues_CreatedById" ON "Issues" ("CreatedById");

CREATE INDEX "IX_Issues_Deleted" ON "Issues" ("Deleted");

CREATE INDEX "IX_Issues_DeletedById" ON "Issues" ("DeletedById");

CREATE INDEX "IX_Issues_Name" ON "Issues" ("Name");

CREATE UNIQUE INDEX "IX_Issues_ProjectId_Number" ON "Issues" ("ProjectId", "Number");

CREATE INDEX "IX_Issues_TypeId" ON "Issues" ("TypeId");

CREATE INDEX "IX_Issues_UpdatedById" ON "Issues" ("UpdatedById");

CREATE UNIQUE INDEX "IX_Issues_Uuid" ON "Issues" ("Uuid");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220503014710_CreateIssueTable', '6.0.4');

COMMIT;
